// BR-01: The official Ticket Number is generated by the backend and must be
// unique. Extracted as a pure function (no DB access) so it is unit
// testable in isolation from ticket creation / Prisma.
export function formatTicketNumber(id: number, date: Date = new Date()): string {
  const year = date.getFullYear();
  const paddedId = id.toString().padStart(6, "0");

  return `TKT-${year}-${paddedId}`;
}
