import { useCallback, useEffect, useState } from "react";
import { getStaffDashboard, type CurrentStatus, type DashboardTicket, type StaffDashboardData } from "../api";

interface Props { name: string; onOpenTicket: (id: number) => void; onViewQueue: (filter?: { status?: CurrentStatus; owner?: "me" | "unassigned"; priority?: "LOW" | "MEDIUM" | "HIGH" }) => void; onSearchTickets: () => void; }

function StatusBadge({ status }: { status: CurrentStatus }) {
  const labels: Record<CurrentStatus, string> = { NEW: "New", OPEN: "Open", IN_PROGRESS: "In Progress", WAITING_FOR_REQUESTER: "Waiting for Requester", RESOLVED: "Resolved", CLOSED: "Closed", REOPENED: "Reopened", CANCELLED: "Cancelled" };
  return <span className="badge rounded-pill" style={{ backgroundColor: "#DCFCE7", color: "#166534" }}>{labels[status]}</span>;
}

function RecentTickets({ tickets, onOpenTicket }: { tickets: DashboardTicket[]; onOpenTicket: (id: number) => void }) {
  return <ul className="list-group list-group-flush">{tickets.map((ticket) => <li className="list-group-item px-0 py-3" key={ticket.id}><div className="row align-items-center g-2"><div className="col-12 col-md-6"><button type="button" className="btn btn-link p-0 text-start fw-semibold" style={{ color: "#166534" }} onClick={() => onOpenTicket(ticket.id)}>{ticket.ticketNumber}</button><div className="small text-truncate">{ticket.summary}</div></div><div className="col-7 col-md-3"><StatusBadge status={ticket.currentStatus} /></div><div className="col-5 col-md-3 small text-muted text-md-end">{new Date(ticket.updatedAt).toLocaleString()}</div></div></li>)}</ul>;
}

export default function StaffDashboard({ name, onOpenTicket, onViewQueue, onSearchTickets }: Props) {
  const [data, setData] = useState<StaffDashboardData | null>(null);
  const [loading, setLoading] = useState(true);
  const [failed, setFailed] = useState(false);
  const load = useCallback(async () => { try { setLoading(true); setFailed(false); setData(await getStaffDashboard()); } catch { setFailed(true); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const primaryCards = data ? [["New", data.byStatus.new, { status: "NEW" as CurrentStatus }], ["Open", data.byStatus.open, { status: "OPEN" as CurrentStatus }], ["In Progress", data.byStatus.inProgress, { status: "IN_PROGRESS" as CurrentStatus }], ["Waiting for Requester", data.byStatus.waitingForRequester, { status: "WAITING_FOR_REQUESTER" as CurrentStatus }], ["My Assigned", data.myAssigned, { owner: "me" as const }]] as const : [];

  return <section aria-labelledby="staff-dashboard-heading"><div className="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4"><div><h2 id="staff-dashboard-heading" className="h3 fw-bold mb-1" style={{ color: "#14231C" }}>Welcome back, {name.split(" ")[0]}!</h2><p className="mb-0 text-muted">Here&apos;s what&apos;s happening with your queue today.</p></div><button type="button" className="btn btn-outline-secondary" onClick={load}>⟳&nbsp; Refresh</button></div>
    {failed && <div className="alert alert-danger" role="alert">We could not load the dashboard. <button type="button" className="btn btn-link p-0" onClick={load}>Try again</button></div>}
    {loading ? <div className="row row-cols-1 row-cols-md-2 row-cols-xl-5 g-3">{[1,2,3,4,5].map((key) => <div className="col" key={key}><div className="card shadow-sm placeholder-glow"><div className="card-body p-4"><span className="placeholder col-7" /><span className="placeholder col-4 d-block mt-4" /></div></div></div>)}</div> : data && <><div className="row row-cols-1 row-cols-md-2 row-cols-xl-5 g-3 mb-4">{primaryCards.map(([label, value, filter]) => <div className="col" key={label}><button type="button" className="card dashboard-card w-100 h-100 text-start shadow-sm" aria-label={`${label}: ${value}. View queue`} onClick={() => onViewQueue(filter)}><div className="card-body p-4"><div className="fw-medium mb-4" style={{ color: "#14231C" }}>{label}</div><div className="display-5 fw-semibold mb-3" style={{ color: "#14231C" }}>{value}</div><span className="small" style={{ color: "#166534" }}>View queue →</span></div></button></div>)}</div>
      <div className="row g-4"><div className="col-12 col-lg-7"><div className="card shadow-sm h-100"><div className="card-body p-0"><div className="d-flex justify-content-between align-items-center px-4 py-3 border-bottom"><h3 className="h5 mb-0">My Recent Tickets</h3><button type="button" className="btn btn-link p-0" style={{ color: "#166534" }} onClick={() => onViewQueue({ owner: "me" })}>View all</button></div><div className="px-4">{data.myRecentTickets.length ? <RecentTickets tickets={data.myRecentTickets} onOpenTicket={onOpenTicket} /> : <p className="text-muted py-4 mb-0">No Tickets are assigned to you yet.</p>}</div></div></div></div><div className="col-12 col-lg-5"><div className="card shadow-sm"><div className="card-body p-4"><h3 className="h5 mb-4">Quick Actions</h3><div className="row g-3"><div className="col-12 col-sm-4"><button type="button" className="dashboard-quick-action" onClick={onSearchTickets}><span className="dashboard-quick-action-icon" aria-hidden="true">⌕</span><span>Search Tickets</span></button></div><div className="col-12 col-sm-4"><button type="button" className="dashboard-quick-action" onClick={() => onViewQueue({ owner: "me" })}><span className="dashboard-quick-action-icon" aria-hidden="true">▣</span><span>My Queue</span></button></div><div className="col-12 col-sm-4"><button type="button" className="dashboard-quick-action dashboard-insight" onClick={() => onViewQueue({ owner: "unassigned" })}><span className="dashboard-quick-action-icon" aria-hidden="true">□</span><span><strong>Unassigned</strong><small>{data.unassigned} active Tickets</small></span></button></div></div></div></div></div></div>
      <div className="card shadow-sm mt-4"><div className="card-body p-4"><h3 className="h6 text-uppercase text-muted mb-3">IT Priority</h3><div className="d-flex gap-2 flex-wrap">{([['Low', data.byItPriority.low, 'LOW'], ['Medium', data.byItPriority.medium, 'MEDIUM'], ['High', data.byItPriority.high, 'HIGH']] as const).map(([label, value, priority]) => <button className="btn btn-outline-success" type="button" key={priority} onClick={() => onViewQueue({ priority })}>{label}: {value}</button>)}</div></div></div>
    </>}</section>;
}
